version: '3.8'

services:
    php-httpd:
        image: php:8.2.1-apache
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        restart: unless-stopped

    mariadb:
        image: mariadb:latest
        volumes:
            - vol-mariadb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "1234567890"
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports:
            - 81:80
        restart: unless-stopped

volumes:
    vol-mariadb:            
