version: '3.8'

services:
    php-httpd:
        image: php:8.2.1-apache
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        restart: unless-stopped

    mariadb:
        image: mariadb:latest
        volumes:
            - single-mariadb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "myrootpass"
            MYSQL_USER: "myuser"
            MYSQL_PASSWORD: "mypass"
            MYSQL_DATABASE: "mydb"
        restart: unless-stopped

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports:
            - 81:80
        restart: unless-stopped

volumes:
    single-mariadb:
